<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                     => __DIR__ . '/Module.php',
    'Application\Form\ApplicationForm'       => __DIR__ . '/src/Application/Form/ApplicationForm.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Model\User'                 => __DIR__ . '/src/Application/Model/User.php',
    'Application\Model\UserTable'            => __DIR__ . '/src/Application/Model/UserTable.php',
);