<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album\Module'                     => __DIR__ . '/Module.php',
    'Album\Form\AlbumForm'             => __DIR__ . '/src/Album/Form/AlbumForm.php',
    'Album\Controller\AlbumController' => __DIR__ . '/src/Album/Controller/AlbumController.php',
    'Album\Model\AlbumTable'           => __DIR__ . '/src/Album/Model/AlbumTable.php',
    'Album\Model\Album'                => __DIR__ . '/src/Album/Model/Album.php',
);