<?php
$title = 'Sign in page';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('controller'=>'index','action' => 'signin')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formRow($form->get('username')) . PHP_EOL;
echo $this->formRow($form->get('password')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

echo $this->escapeHtml("Don't have account ?");
?>
<p><a href="<?php echo $this->url('user', array('controller'=>'index','action'=>'signup'));?>">Click here</a></p>

