<?php
$title = 'Registration page';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('user', array('controller'=>'index','action' => 'signup')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formRow($form->get('fname')) . PHP_EOL;
echo $this->formRow($form->get('lname')) . PHP_EOL;
echo $this->formRow($form->get('user')) . PHP_EOL;
echo $this->formRow($form->get('pass')) . PHP_EOL;
echo $this->formRow($form->get('fileupload')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

